//Importing CSS
import "./css/reset.css";
import "./css/base.css";
import "./css/layout/theme.css";
import "./css/style.css";
import "./css/server.css";
import "./css/core/data/data.css";
import "./css/core/data/table.css";
import "./css/core/data/data_details.css";
import "./css/core/data/context_menu.css";
import "./css/core/data/custom_paint.css";
import "./css/core/input.css";
import "./css/core/script/scripts.css";
import "./css/id.css";
import "./css/configure.css";
import "./css/profile.css";
import "./css/core/libs/file_save.css";
import "./css/options_menu.css";
//import "./css/esp32_mesh_script.css";
import "./css/local_app.css";
import "./css/extra/tools.css";
        
//Importing components
//import "./js/libs/third/d3.v5.min.js";
import "./js/components/modal.js";
import "./js/components/slide_menu_hover.js";
import "./js/components/retract_menu.js";
import "./js/components/tabs.js";
import "./js/components/draggable.js";
import "./js/components/drop_menu.js";
import "./js/components/input_mac.js";
import "./js/components/input_x.js";
import "./js/components/input_ipv4.js";
import "./js/components/input_option.js";
import "./js/components/optional-container.js";
import "./js/components/input-resize.js";
import "./js/components/custom-protocol.js";
import "./js/components/closeable-status.js";
import "./js/components/w_container.js";
import "./js/components/select-checkbox.js";
import "./js/components/json-message.js";
import "./js/components/convert-container.js";
import "./js/components/context-menu.js";
import "./js/components/input_socket_ipv4.js";
import "./js/components/input_url.js";
import "./js/components/esp32_br_input/esp32_br_input.js";

//Main file
import "./js/main.js";
